version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.3.0
    - 3.3.1
  - dependency-name: netlify-cms-app
    versions:
    - 2.14.37
    - 2.14.40
    - 2.14.41
    - 2.14.45
    - 2.14.46
  - dependency-name: gatsby-remark-images
    versions:
    - 5.0.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.3.0
  - dependency-name: gatsby-plugin-sass
    versions:
    - 4.3.0
  - dependency-name: gatsby-plugin-algolia
    versions:
    - 0.18.2
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
