version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: dockerfile
      target: build
    image: danydodson/danydodson-dev:1.0
    tty: true
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/
    volumes:
      - .:/usr/src/app
      - cache:/usr/src/app/.cache
      - public:/usr/src/app/public
      - node_modules:/usr/src/app/node_modules
    ports:
      - 8080:8080
    networks:
      - frontend

volumes:
  cache:
  public:
  node_modules:

networks:
  frontend:
