backend:
  name: git-gateway
  branch: main
  repo: danydodson/dev

media_folder: static/assets

public_folder: assets

collections:
  - name: posts
    label: 'Blog'
    folder: 'content/blogs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}--{{slug}}'
    media_folder: ''
    public_folder: ''
    path: '{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Priority', name: 'priority', widget: 'number', default: 0, valueType: 'int' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: pages
    label: 'Page'
    folder: 'content/pages'
    create: true
    media_folder: ''
    public_folder: ''
    slug: '{{slug}}'
    path: '{{slug}}/index'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Cover Image', name: 'cover', widget: 'image' }
      - { label: 'Priority', name: 'priority', widget: 'number', default: 0, valueType: 'int' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'string', default: 'info' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: 'info' }
